steps:
#### build and push Docker image if not existing yet
- name: "google/cloud-sdk:slim"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Received _MY_IMAGE_TAG: ${_MY_IMAGE_TAG}"
    echo "Cloud Build's default SHORT_SHA (for reference, not used for tagging): '${SHORT_SHA}'"
    echo "Cloud Build's default COMMIT_SHA (for reference): '${COMMIT_SHA}'"

    # Configure Docker to authenticate with Artifact Registry
    gcloud auth configure-docker europe-docker.pkg.dev --quiet
    
    # Construct the full image name using the explicitly passed _MY_IMAGE_TAG
    TARGET_IMAGE="europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}"
    IMAGE_REPO_PATH="europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application" # For the list command

    echo "Checking if image $${TARGET_IMAGE} exists..."
    # Use _MY_IMAGE_TAG for filtering
    if ! gcloud artifacts docker images list "$${IMAGE_REPO_PATH}" --filter="tags~'^${_MY_IMAGE_TAG}$'" --format="value(tags)" | grep -q "^${_MY_IMAGE_TAG}$"; then
      echo "Image $${TARGET_IMAGE} not found. Building and pushing..."
      docker build -t "$${TARGET_IMAGE}" cloud-run/application/
      docker push "$${TARGET_IMAGE}"
      echo "Image $${TARGET_IMAGE} built and pushed."
    else
      echo "Image $${TARGET_IMAGE} already exists. Skipping build and push."
    fi

#### run safety check
- name: "gcr.io/cloud-builders/docker"
  args:
  - "run"
  - "--entrypoint"
  - "bash"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}" # USE _MY_IMAGE_TAG
  - "-c"
  - "pip install safety && safety check --bare || true"

#### run unittests
- name: "gcr.io/cloud-builders/docker"
  args:
  - "run"
  - "--entrypoint"
  - "python"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}" # USE _MY_IMAGE_TAG
  - "-m"
  - "unittest"
  - "discover"
  - "-p"
  - "test_*.py"

#### run integration tests
- name: "gcr.io/cloud-builders/docker"
  args:
  - "run"
  - "--network"
  - "cloudbuild"
  - "--env"
  - "PYTHONPATH=/home"
  - "--env"
  - "PROJECT_ID=${PROJECT_ID}"
  - "--env"
  - "K_REVISION=cloudbuild"
  - "--entrypoint"
  - "bash"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}" # USE _MY_IMAGE_TAG
  - "-c"
  - "/usr/bin/Xvfb :0 -ac -screen 0 1024x768x16 +extension RANDR & export DISPLAY=:0 && python ./_tests/integration_tests.py"

#### deploy new revision
- name: 'gcr.io/cloud-builders/gcloud-slim'
  args:
  - "run"
  - "deploy"
  - "ib-${_TRADING_MODE}"
  - "--image"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}" # USE _MY_IMAGE_TAG
  - "--region"
  - "${_GCP_REGION}"
  - "--platform"
  - "managed"
  - "--max-instances"
  - "1"
  - "--memory"
  - "2Gi"
  - "--service-account"
  - "ib-trading@${PROJECT_ID}.iam.gserviceaccount.com"
  - "--revision-suffix"
  - "${_MY_IMAGE_TAG}" # USE _MY_IMAGE_TAG
  - "--update-labels"
  - "app=ib-trading,trading-mode=${_TRADING_MODE}"
  - "--update-env-vars"
  - "PROJECT_ID=${PROJECT_ID},TRADING_MODE=${_TRADING_MODE}"

#### delete old revision(s)
- name: "gcr.io/cloud-builders/gcloud-slim"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    set -e 
    if [[ "${_KEEP}" -gt "0" ]]; then
      echo "Cleaning up old revisions for service ib-${_TRADING_MODE} in region ${_GCP_REGION}, keeping last ${_KEEP} active revisions..."
      
      ALL_REVISIONS_ARR=($(gcloud run revisions list \
        --service="ib-${_TRADING_MODE}" \
        --platform="managed" \
        --region="${_GCP_REGION}" \
        --filter="metadata.labels.trading-mode=${_TRADING_MODE}" \
        --sort-by="~metadata.creationTimestamp" \
        --format="value(metadata.name)"))

      echo "Found revisions: $${ALL_REVISIONS_ARR[@]}"

      SHELL_RE_NUM='^[0-9]+$'
      if ! [[ "${_KEEP}" =~ $$SHELL_RE_NUM ]] ; then
         echo "Error: _KEEP is not a number" >&2; exit 1
      fi

      REVISIONS_TO_DELETE_ARR=()
      if [ "$${#ALL_REVISIONS_ARR[@]}" -gt "${_KEEP}" ]; then
        REVISIONS_TO_DELETE_ARR=($${ALL_REVISIONS_ARR[@]:$_KEEP})
      fi

      if [ "$${#REVISIONS_TO_DELETE_ARR[@]}" -gt 0 ]; then
        echo "The following revisions will be deleted: $${REVISIONS_TO_DELETE_ARR[@]}"
        for shell_revision_var in "$${REVISIONS_TO_DELETE_ARR[@]}"; do
          echo "Deleting revision: $${shell_revision_var}"
          yes | gcloud run revisions delete "$${shell_revision_var}" --platform="managed" --region="${_GCP_REGION}" --quiet
        done
      else
        echo "No old revisions to delete beyond the _KEEP=${_KEEP} limit."
      fi

      echo "Cleaning up unused Docker image tags..."
      ACTIVE_REVISION_TAGS_ARR=()
      for shell_rev_name_var in "$${ALL_REVISIONS_ARR[@]:0:$_KEEP}"; do
        shell_img_url_var=$(gcloud run revisions describe "$${shell_rev_name_var}" --platform="managed" --region="${_GCP_REGION}" --format="value(spec.template.spec.containers[0].image)")
        shell_tag_var=$(echo "$${shell_img_url_var}" | rev | cut -d: -f1 | rev)
        if [[ -n "$${shell_tag_var}" && "$${shell_tag_var}" != "latest" ]]; then # Be careful if 'latest' is a valid tag you might use via _MY_IMAGE_TAG
             ACTIVE_REVISION_TAGS_ARR+=("$${shell_tag_var}")
        fi
      done
      
      # Use _MY_IMAGE_TAG here instead of SHORT_SHA
      # This ensures the currently built/deployed image tag is considered "active"
      if [[ ! " $${ACTIVE_REVISION_TAGS_ARR[@]} " =~ " ${_MY_IMAGE_TAG} " ]]; then
        ACTIVE_REVISION_TAGS_ARR+=("${_MY_IMAGE_TAG}") 
      fi
      
      ACTIVE_REVISION_TAGS_UNIQUE_ARR=($(echo "$${ACTIVE_REVISION_TAGS_ARR[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
      echo "Active or recent revision tags to keep: $${ACTIVE_REVISION_TAGS_UNIQUE_ARR[@]}"

      ALL_IMAGE_TAGS_ARR=($(gcloud artifacts docker images list "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application" --format="value(tags)" --filter="tags:*"))
      echo "All image tags in repository: $${ALL_IMAGE_TAGS_ARR[@]}"

      for shell_tag_iter_var in $${ALL_IMAGE_TAGS_ARR[@]}; do
        # Avoid deleting 'latest' if it's explicitly used or if _MY_IMAGE_TAG could be 'latest'
        if [[ -z "$${shell_tag_iter_var}" ]] || ([[ "$${shell_tag_iter_var}" == "latest" ]] && [[ "${_MY_IMAGE_TAG}" != "latest" ]]); then
          # Skip empty tags. Skip 'latest' UNLESS _MY_IMAGE_TAG itself is 'latest' (then it's handled by ACTIVE_REVISION_TAGS_UNIQUE_ARR logic).
          # This logic is a bit tricky: if _MY_IMAGE_TAG is 'latest', it will be in ACTIVE_REVISION_TAGS_UNIQUE_ARR and won't be deleted.
          # If _MY_IMAGE_TAG is something else, and there's an unrelated 'latest' tag, this 'if' condition might need adjustment
          # depending on whether you want to preserve a generic 'latest' tag.
          # For simplicity, if _MY_IMAGE_TAG could be 'latest', we ensure 'latest' is handled by the keep list.
          # If 'latest' is just a floating tag you want to prune if unused, this is more complex.
          # A safer bet: if a tag is 'latest' and _MY_IMAGE_TAG is NOT 'latest', we might want to keep 'latest' or explicitly delete it.
          # The current logic will try to delete an old 'latest' tag if _MY_IMAGE_TAG is something else and 'latest' is not in recent revisions.
          if [[ "$${shell_tag_iter_var}" == "latest" && "${_MY_IMAGE_TAG}" != "latest" ]]; then
             echo "Skipping deletion of general 'latest' tag as it's not the current build tag."
             continue # Or implement specific logic if you want to prune 'latest'
          fi
          if [[ -z "$${shell_tag_iter_var}" ]]; then
              continue
          fi
        fi

        SHELL_SHOULD_KEEP_BOOL=false 
        for shell_keep_tag_var in $${ACTIVE_REVISION_TAGS_UNIQUE_ARR[@]}; do
          if [[ "$${shell_tag_iter_var}" == "$${shell_keep_tag_var}" ]]; then
            SHELL_SHOULD_KEEP_BOOL=true
            break
          fi
        done

        if ! $${SHELL_SHOULD_KEEP_BOOL}; then
          echo "Deleting image tag: europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:$${shell_tag_iter_var}"
          yes | gcloud artifacts docker images delete "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:$${shell_tag_iter_var}" --delete-tags --quiet
        fi
      done
    else
      echo "Skipping cleanup of old revisions and image tags as _KEEP is not greater than 0."
    fi

substitutions:
  _GCP_REGION: europe-west6
  _TRADING_MODE: paper 
  _KEEP: "3" 
  _MY_IMAGE_TAG: "latest" # Default value for _MY_IMAGE_TAG

timeout: "1200s"