# ===================================================================
# == FINAL CORRECTED: cloud-run/application/cloudbuild.yaml
# ===================================================================

steps:
  # 步骤 1: 拉取最新的 base 镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull-Latest-Base'
    args: ['pull', 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/base:latest']

  # 步骤 2: 构建 application 镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-Application'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE_URL=europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/base:latest'
      - '--tag'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}'
      - 'cloud-run/application'
      - '--file'
      - 'cloud-run/application/Dockerfile'
    waitFor: ['Pull-Latest-Base']

  # 步骤 3: 推送 application 镜像
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push-Application'
    args: ['push', 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}']
    waitFor: ['Build-Application']

  # --- 检测和初始化步骤 ---

  # 步骤 4: 运行依赖安全检查 (优化后)
  - name: "gcr.io/cloud-builders/docker"
    id: "Safety-Check"
    args:
      - "run"
      - "--rm"
      - "--entrypoint"
      - "bash"
      - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}"
      - "-c"
      - "pip install --quiet safety && safety check --bare"
    waitFor: ['Push-Application']

  # 步骤 5: 运行单元测试 (已修复)
  - name: "gcr.io/cloud-builders/gcloud" # <--- 关键修复：使用 gcloud builder
    id: "Unit-Tests"
    entrypoint: "bash"
    args:
    - "-c"
    - |
      docker run --rm \
        --env "PROJECT_ID=${PROJECT_ID}" \
        --env "TRADING_MODE=${_TRADING_MODE}" \
        --env "GOOGLE_APPLICATION_CREDENTIALS=/gcloud-credentials/application_default_credentials.json" \
        -v "gcloud-config:/gcloud-credentials" \
        --entrypoint python \
        europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG} \
        -m unittest discover -p "test_*.py"
    volumes:
      - name: 'gcloud-config'
        path: '/gcloud-credentials'
    waitFor: ['Push-Application']


  # 步骤 6: 初始化 Firestore 配置
  - name: 'python:3.9-slim'
    id: "Initialize-Firestore"
    entrypoint: 'bash'
    args:
    - -c
    - |
      set -e
      pip install --quiet google-cloud-firestore
      python cloud-run/application/app/lib/init_firestore.py "${PROJECT_ID}"
    waitFor: ['Push-Application']

  # 步骤 7: 运行集成测试 (已修复)
  - name: "gcr.io/cloud-builders/gcloud" # <--- 关键修复：使用 gcloud builder
    id: "Integration-Tests"
    entrypoint: "bash"
    args:
    - "-c"
    - |
      docker run --rm \
        --env "PYTHONPATH=/home" \
        --env "PROJECT_ID=${PROJECT_ID}" \
        --env "TRADING_MODE=${_TRADING_MODE}" \
        --env "K_REVISION=cloudbuild" \
        --env "GOOGLE_APPLICATION_CREDENTIALS=/gcloud-credentials/application_default_credentials.json" \
        -v "gcloud-config:/gcloud-credentials" \
        --entrypoint bash \
        europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG} \
        -c "/usr/bin/Xvfb :0 -ac -screen 0 1024x768x16 +extension RANDR & export DISPLAY=:0 && python ./_tests/integration_tests.py"
    volumes:
      - name: 'gcloud-config'
        path: '/gcloud-credentials'
    waitFor: ['Initialize-Firestore']

  # --- 部署步骤 ---

  # 步骤 8: 部署到 Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy-to-Cloud-Run'
    args:
      - 'run'
      - 'deploy'
      - 'ib-${_TRADING_MODE}'
      - '--image'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}'
      - '--region'
      - '${_GCP_REGION}'
      - '--platform'
      - 'managed'
      - '--max-instances'
      - '1'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--service-account'
      - 'ib-trading@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=PROJECT_ID=${PROJECT_ID},TRADING_MODE=${_TRADING_MODE}'
    waitFor:
      - 'Safety-Check'
      - 'Unit-Tests'
      - 'Integration-Tests'

# 替换变量
substitutions:
  _GCP_REGION: asia-east1
  _TRADING_MODE: paper
  _MY_IMAGE_TAG: "latest"

timeout: "1800s"