steps:
#### build and push Docker image if not existing yet
- name: "gcr.io/cloud-builders/gcloud-slim"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    # Check if image with tag exists in Artifact Registry
    if ! gcloud artifacts docker images list europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo --filter="tags~'${SHORT_SHA}'" --format="value(tags)" | grep -q "${SHORT_SHA}"; then
      # Build and push to Artifact Registry
      gcloud builds submit \
        --tag europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${SHORT_SHA} \
        --gcs-source-staging-dir gs://${PROJECT_ID}-cloudbuild/source \
        --substitutions SHORT_SHA=${SHORT_SHA} \
        cloud-run/application/
    fi
#### run safety check
- name: "gcr.io/cloud-builders/docker"
  args:
  - "run"
  - "--entrypoint"
  - "bash"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${SHORT_SHA}"
  - "-c"
  - "pip install safety && safety check --bare"
#### run unittests
- name: "gcr.io/cloud-builders/docker"
  args:
  - "run"
  - "--entrypoint"
  - "python"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${SHORT_SHA}"
  - "-m"
  - "unittest"
  - "discover"
  - "-p"
  - "test_*.py"
#### run integration tests
- name: "gcr.io/cloud-builders/docker"
  args:
  - "run"
  - "--network"
  - "cloudbuild"
  - "--env"
  - "PYTHONPATH=/home"
  - "--env"
  - "PROJECT_ID=${PROJECT_ID}"
  - "--env"
  - "K_REVISION=cloudbuild"
  - "--entrypoint"
  - "bash"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${SHORT_SHA}"
  - "-c"
  - "/usr/bin/Xvfb $$DISPLAY -ac -screen 0 1024x768x16 +extension RANDR & python ./_tests/integration_tests.py"
#### deploy new revision
- name: 'gcr.io/cloud-builders/gcloud-slim'
  args:
  - "run"
  - "deploy"
  - "ib-${_TRADING_MODE}"
  - "--image"
  - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${SHORT_SHA}"
  - "--region"
  - "${_GCP_REGION}"
  - "--platform"
  - "managed"
  - "--max-instances"
  - "1"
  - "--memory"
  - "2Gi"
  - "--service-account"
  - "ib-trading@${PROJECT_ID}.iam.gserviceaccount.com"
  - "--revision-suffix"
  - "${SHORT_SHA}"
  - "--update-labels"
  - "app=ib-trading,trading-mode=${_TRADING_MODE}"
  - "--update-env-vars"
  - "PROJECT_ID=${PROJECT_ID},TRADING_MODE=${_TRADING_MODE}"
#### delete old revision(s)
- name: "gcr.io/cloud-builders/gcloud-slim"
  entrypoint: "bash"
  args:
  - "-c"
  - |
    if [[ "${_KEEP}" > "0" ]]
    then
      REVISIONS=($(gcloud run revisions list --platform managed --region ${_GCP_REGION} --filter "metadata.labels.trading-mode=${_TRADING_MODE} AND (status.conditions.status=False OR status.conditions.status=Unknown)" --sort-by ~metadata.creationTimestamp --format "value(metadata.name)"))
      for revision in "$${REVISIONS[@]:$_KEEP}"
      do
        # echo "gcloud run revisions delete $${revision}"
        yes | gcloud run revisions delete $${revision} --platform managed --region ${_GCP_REGION}
      done

      REVISION_TAGS=($(gcloud run revisions list --platform managed --region ${_GCP_REGION} --sort-by ~metadata.creationTimestamp --format "value(metadata.name)" | rev | cut -d- -f1 | rev))
      if [[ ! "$${REVISION_TAGS[@]}" =~ "${SHORT_SHA}" ]]
      then
        REVISION_TAGS=("${SHORT_SHA}" $${REVISION_TAGS[@]})
      fi
      IMAGE_TAGS=($(gcloud artifacts docker images list europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application --format "value(tags)"))
      for tag in "$${IMAGE_TAGS[@]}"
      do
        if [[ ! "$${REVISION_TAGS[@]}" =~ "$${tag}" ]]
        then
          # echo "gcloud artifacts docker images delete europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:$${tag}"
          yes | gcloud artifacts docker images delete europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:$${tag}
        fi
      done
    fi
substitutions:
  _GCP_REGION: europe-west6
  _KEEP: "3"
