# ===================================================================
# == CORRECTED & ROBUST: cloud-run/application/cloudbuild.yaml
# == Injects secrets as environment variables for the gateway.
# ===================================================================

steps:
  # 步骤 0: Pull-Latest-Base
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull-Latest-Base'
    args: ['pull', 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/base:latest']

  # 步骤 1: Build-Application
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build-Application'
    args:
      - 'build'
      - '--build-arg'
      - 'BASE_IMAGE_URL=europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/base:latest'
      - '--tag'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}'
      - 'cloud-run/application'
      - '--file'
      - 'cloud-run/application/Dockerfile'
    waitFor: ['Pull-Latest-Base']

  # 步骤 2: Push-Application
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push-Application'
    args: ['push', 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}']
    waitFor: ['Build-Application']

  # --- 检测和初始化步骤 ---

  # 步骤 4: 运行依赖安全检查 (允许继续，即使发现漏洞)
  - name: "gcr.io/cloud-builders/docker"
    id: "Safety-Check"
    args:
      - "run"
      - "--rm"
      - "--entrypoint"
      - "bash"
      - "europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}"
      - "-c"
      - "pip install --quiet safety && safety check --bare || true"
    waitFor: ['Push-Application']

  # 步骤 5: 运行单元测试 (当前跳过)
  - name: "gcr.io/google/cloud-sdk:slim"
    id: "Unit-Tests"
    entrypoint: "bash"
    args: ["-c", "echo '--- SKIPPING UNIT TESTS ---' && exit 0"]
    waitFor: ['Push-Application']

  # 步骤 6: 初始化 Firestore 配置
  - name: 'python:3.9-slim'
    id: "Initialize-Firestore"
    entrypoint: 'bash'
    args:
    - -c
    - |
      set -e
      pip install --quiet google-cloud-firestore
      python cloud-run/application/app/lib/init_firestore.py "${PROJECT_ID}"
    waitFor: ['Push-Application']

  # 步骤 7: 运行集成测试 (当前跳过)
  - name: "gcr.io/google/cloud-sdk:slim"
    id: "Integration-Tests"
    entrypoint: "bash"
    args: ["-c", "echo '--- SKIPPING INTEGRATION TESTS ---' && exit 0"]
    waitFor: ['Initialize-Firestore']

  # --- 部署步骤 ---

  # 步骤 8: 部署到 Cloud Run
  - name: 'gcr.io/google/cloud-sdk'
    id: 'Deploy-to-Cloud-Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ib-${_TRADING_MODE}'
      - '--image'
      - 'europe-docker.pkg.dev/${PROJECT_ID}/cloud-run-repo/application:${_MY_IMAGE_TAG}'
      - '--region'
      - '${_GCP_REGION}'
      - '--platform'
      - 'managed'
      - '--max-instances'
      - '1'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--service-account'
      - 'ib-trading@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'
      # 关键修复：将环境变量和 Secrets 分开设置
      - '--set-env-vars=PROJECT_ID=${PROJECT_ID},TRADING_MODE=${_TRADING_MODE},TWS_VERSION=1030'
      # 关键修复：从 Secret Manager 安全地注入凭据作为环境变量
      # 注意：您需要在 GCP Secret Manager 中创建名为 'ib-username' 和 'ib-password' 的 Secret
      - '--set-secrets=IB_USERNAME=ib-username:latest,IB_PASSWORD=ib-password:latest'
    waitFor:
      - 'Safety-Check'
      - 'Unit-Tests'
      - 'Integration-Tests'

# 替换变量
substitutions:
  _GCP_REGION: asia-east1
  _TRADING_MODE: paper
  _MY_IMAGE_TAG: "latest"

timeout: "1800s"